using AppPipe.Hosting;

namespace AppPipeProjectTest.AppHost;

internal class Program
{
    private static async Task Main(string[] args)
    {
        // 1. Initialize the builder
        var builder = AppPipeHostingApp.CreateBuilder(args);

        // Configure the Gateway Host itself
        builder.HostProject = new AppPipeHostingProjectResource("AppPipeProjectTest.AppHost", "");
        builder.HostProject.WithEndpoint(7151)
                           .WithAppPath("/AppPipeProjectTest.AppHost")
                           .WithEnvironment("LOG_LEVEL", "Debug");

        // 2. Add backend and frontend projects using compile-safe constants
        // These constants are generated by AppPipe.Hosting.targets packaged inside the NuGet.
        var apiService = builder.AddProject(AppPipeProjects.AppPipeProjectTest_ApiService)
                                .WithEndpoint(7152)
                                .WithAppPool("AppPipeProjectTestApiServicePool")
                                .WithIISSite("Default Web Site")
                                .WithAppPath("/ApiService")
                                .WithServiceDisplayName("AppPipe ApiService")
                                .WithServiceDescription("AppPipe API Service Backend")
                                .WithServiceStartType("auto");

        var web = builder.AddProject(AppPipeProjects.AppPipeProjectTest_Web)
                         .WithReference(apiService)
                         .WithEndpoint(7153)
                         .WithAppPool("AppPipeProjectTestWebPool")
                         .WithIISSite("Default Web Site")
                         .WithAppPath("/Web")
                         .WithServiceDisplayName("AppPipe Web Frontend")
                         .WithServiceDescription("AppPipe Web Frontend UI")
                         .WithServiceStartType("auto");

        // 3. Build the graph
        var app = builder.Build();

        // 4. Handle run modes and deployment
        if (args.Length > 0 && (args[0] == "deploy" || args[0] == "deploy-service" || args[0] == "--deploy"))
        {
            var target = DeploymentTarget.IIS;
            var deployPath = "";

            if (args[0] == "--deploy")
            {
                var targetStr = args.Length > 1 ? args[1] : "iis";
                deployPath = args.Length > 2 ? args[2] : "";

                if (targetStr.Equals("iis", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.IIS;
                }
                else
                {
                    throw new ArgumentException($"Unsupported deployment target: {targetStr}");
                }
            }

            await OnPremDeployer.CompileToOnPremAsync(app, target, deployPath);
        }
        else if (Environment.GetEnvironmentVariable("APP_POOL_ID") != null ||
                 Environment.GetEnvironmentVariable("WINDOWS_SERVICE") == "true" ||
                 Environment.GetEnvironmentVariable("LINUX_SERVICE") == "true")
        {
            var gateway = new GatewayAppPipeHost();
            await gateway.StartAsync(string.Empty, app, app.ConfigureGatewayAction);
            await Task.Delay(-1);
        }
        else
        {
            var runner = new AppPipeDevHostRunner(app);
            await runner.RunAsync();
        }
    }
}
