using AppPipe.Hosting;

namespace AppPipeSystem.AppHost;

internal class Program
{
    private static async Task Main(string[] args)
    {
        // 1. Initialize the builder
        var builder = AppPipeHostingApp.CreateBuilder(args);

        // Configure the Gateway Host itself
        builder.HostProject = new AppPipeHostingProjectResource(AppPipeProjects.HostProject);
        builder.HostProject.WithEndpoint(7001)
                           .WithAppPath("/AppPipeSystem.AppHost")
                           .WithEnvironment("LOG_LEVEL", "Debug");

        // 2. Add backend and frontend projects using compile-safe constants
        // These constants are generated by AppPipe.Hosting.targets packaged inside the NuGet.
        var BackendApi = builder.AddProject(AppPipeProjects.AppPipeSystem_BackendApi)
                                .WithEndpoint(7002)
                                .WithAppPool("AppPipeSystemBackendApiPool")
                                .WithIISSite("Default Web Site")
                                .WithAppPath("/BackendApi")
                                .WithServiceDisplayName("AppPipe BackendApi")
                                .WithServiceDescription("AppPipe API Service Backend")
                                .WithServiceStartType("auto");

        var web = builder.AddProject(AppPipeProjects.AppPipeSystem_Web)
                         .WithReference(BackendApi)
                         .WithEndpoint(7003)
                         .WithAppPool("AppPipeSystemWebPool")
                         .WithIISSite("Default Web Site")
                         .WithAppPath("/Web")
                         .WithServiceDisplayName("AppPipe Web Frontend")
                         .WithServiceDescription("AppPipe Web Frontend UI")
                         .WithServiceStartType("auto");

        // 3. Build the graph
        var app = builder.Build();

        // 4. Handle run modes and deployment
        if (args.Length > 0 && (args[0] == "deploy" || args[0] == "deploy-service" || args[0] == "--deploy"))
        {
            var target = DeploymentTarget.IIS;
            var deployPath = "";

            if (args[0] == "deploy-service")
            {
                target = DeploymentTarget.WindowsService;
                deployPath = args.Length > 1 ? args[1] : "";
            }
            else if (args[0] == "--deploy")
            {
                var targetStr = args.Length > 1 ? args[1] : "iis";
                deployPath = args.Length > 2 ? args[2] : "";

                if (targetStr.Equals("windows-service", StringComparison.OrdinalIgnoreCase) || targetStr.Equals("service", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.WindowsService;
                }
                else if (targetStr.Equals("iis", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.IIS;
                }
                else if (targetStr.Equals("iis-shared", StringComparison.OrdinalIgnoreCase) || targetStr.Equals("shared", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.IISSharedHosting;
                }
                else if (targetStr.Equals("linux-service", StringComparison.OrdinalIgnoreCase) || targetStr.Equals("systemd", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.LinuxService;
                }
                else if (targetStr.Equals("linux-nginx", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.LinuxNginx;
                }
                else if (targetStr.Equals("linux-caddy", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.LinuxCaddy;
                }
                else
                {
                    throw new ArgumentException($"Unknown deployment target: {targetStr}");
                }
            }
            else // "deploy"
            {
                target = DeploymentTarget.IIS;
                deployPath = args.Length > 1 ? args[1] : "";
            }

            await OnPremDeployer.CompileToOnPremAsync(app, target, deployPath);
        }
        else if (Environment.GetEnvironmentVariable("APP_POOL_ID") != null ||
                 Environment.GetEnvironmentVariable("WINDOWS_SERVICE") == "true" ||
                 Environment.GetEnvironmentVariable("LINUX_SERVICE") == "true")
        {
            var gateway = new GatewayAppPipeHost();
            await gateway.StartAsync(string.Empty, app, app.ConfigureGatewayAction);
            await Task.Delay(-1);
        }
        else
        {
            var runner = new AppPipeDevHostRunner(app);
            await runner.RunAsync();
        }
    }
}

