using AppPipe.Hosting;

namespace NugetConsumer;

internal class Program
{
    private static async Task Main(string[] args)
    {
        // 1. Initialize the builder
        var builder = AppPipeApp.CreateBuilder(args);

        // Configure the host project explicitly
        builder.HostProject = new ProjectResource("NugetConsumer", "");
        builder.HostProject.WithEndpoint(7001)
                           .WithAppPath("/NugetConsumer")
                           .WithEnvironment("LOG_LEVEL", "Debug");

        // 2. Add backend and frontend projects using code-generated constants
        // These constants are generated by AppPipe.Hosting.targets packaged inside the NuGet.
        var backend = builder.AddProject(Projects.BackendWorker)
                             .WithEndpoint(7002)
                             .WithAppPool("NugetConsumerBackendPool")
                             .WithIISSite("Default Web Site")
                             .WithAppPath("/BackendWorker")
                             .WithServiceDisplayName("Nuget Consumer Backend")
                             .WithServiceDescription("AppPipe Backend Worker via Nuget package")
                             .WithServiceStartType("auto");

        var frontend = builder.AddProject(Projects.FrontendApi)
                              .WithReference(backend)
                              .WithEndpoint(7003)
                              .WithAppPool("NugetConsumerFrontendPool")
                              .WithIISSite("Default Web Site")
                              .WithAppPath("/FrontendApi")
                              .WithServiceDisplayName("Nuget Consumer Frontend")
                              .WithServiceDescription("AppPipe Frontend API via Nuget package")
                              .WithServiceStartType("auto");

        // 3. Build the graph
        var app = builder.Build();

        if (args.Length > 0 && (args[0] == "deploy" || args[0] == "deploy-service" || args[0] == "--deploy"))
        {
            var target = DeploymentTarget.IIS;
            var deployPath = "";

            if (args[0] == "--deploy")
            {
                var targetStr = args.Length > 1 ? args[1] : "iis";
                deployPath = args.Length > 2 ? args[2] : "";

                if (targetStr.Equals("iis", StringComparison.OrdinalIgnoreCase))
                {
                    target = DeploymentTarget.IIS;
                }
                else
                {
                    throw new ArgumentException($"Unsupported deployment target in consumer sample: {targetStr}");
                }
            }

            await OnPremDeployer.CompileToOnPremAsync(app, target, deployPath);
        }
        else
        {
            var runner = new DevHostRunner(app);
            await runner.RunAsync();
        }
    }
}
